### ISSUE TITLE
Please add support for Trakt.tv

### ISSUE THREAD

**Issue by profucius** [debridmediamanager/browser-extension#1]
Hi there. Love this extension! I use it on IMDB often. Would you be willing to add Trakt.tv support? I am on this site more often than IMDB and having direct access would be so amazing for the community! 

For instance in my screenshot below you can see the Overseer request extension doing a similar thing as yours does on IMDB. 

![image](https://github.com/debridmediamanager/browser-extension/assets/18254607/a21e0d7a-b4bf-4b50-b4a6-4b7f9320f6a9)

**Comment by yowmamasita** [comment]
This is now done :)

**Comment by profucius** [comment]
You sir are amazing. Thank you so much!
